#!/bin/bash
cd /Arduino
# /Arduino/virtual_env/bin/python manage.py runworker --threads 2 --only-channels=websocket.*
/Arduino/virtual_env/bin/python manage.py runworker --threads 2 | /usr/bin/tee -a /Arduino/runworker.log
